---
version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=django_app
      - POSTGRES_PASSWORD=django_app
      - POSTGRES_DB=django_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_app"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./
    entrypoint: ./setup_server.sh
    volumes:
      - ./nl_map_app:/app_docker
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgis_data:
